### ISSUE TITLE
no module named xmlrpclib

### ISSUE THREAD

**Issue by yutiansut** [ajdavis/motor-blog#45]
```
λ  python server.py --debug --config=motor_blog.conf --ensure-indexes
Traceback (most recent call last):
  File "server.py", line 16, in <module>
    from motor_blog import indexes, cache, application
  File "E:\blogsys\motor-blog\motor_blog\application.py", line 9, in <module>
    from motor_blog.api.handlers import APIHandler, RSDHandler
  File "E:\blogsys\motor-blog\motor_blog\api\__init__.py", line 4, in <module>
    import xmlrpclib
ModuleNotFoundError: No module named 'xmlrpclib'
```
and tring to use pip install but error
```
E:\blogsys\motor-blog [master ≡ +0 ~3 -0 !]
λ  pip install xmlrpclib
Collecting xmlrpclib
  Could not find a version that satisfies the requirement xmlrpclib (from versions: )
No matching distribution found for xmlrpclib
```

**Comment by yutiansut** [comment]
fixed for python3 has changed api

see [xmlrpclib](https://docs.python.org/2/library/xmlrpclib.html)

so change the code from
```
import xmlrpclib
```

to

 
```
import xmlrpc.client as xmlrpclib
```

**Comment by ajdavis** [comment]
Do you want to submit a pull request that handles this problem?

**Comment by yutiansut** [comment]
@ajdavis maybe i need sometime to fix  py2-py3 has lots of thing to fix~

**Comment by yutiansut** [comment]
@ajdavis  my environment is py3.6 while i finish i'll make a pr to U ^-^

**Comment by ajdavis** [comment]
I’m no longer maintaining this. If you decide to make it pure Python 3 and
drop Python 2, go for it.

**Comment by yutiansut** [comment]
all right thx~
